name: Build Kernel op5
on:
  push:
    branches:    
      - blu_spark-10
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: false
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Init Repo
      run: |
        cd ~
        git clone https://github.com/Blankeer/op5 -b blu_spark-10 --depth=1 
    - name: Build With Shell
      run: |
        cd ~/op5
        bash build_full.sh
    - name: Package With AnyKernel
      run: |
        cd ~
        cd AnyKernel/
        cp ../op5/out/arch/arm64/boot/Image.gz-dtb  ./
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: op5_blu_spark_blanke
        path: /home/runner/AnyKernel/
